In [1]:
%load_ext autoreload
%autoreload 2

In [11]:
import json
import os
import time
import glob

In [70]:
from dataset.screwing_dataset import ScrewingDataset

In [57]:
from torch.utils.data import DataLoader, ConcatDataset
import torch

In [27]:
base_dset_dir = os.path.expanduser('~/datasets/screwing')

# xprmnt_dir = time.strftime("/%Y-%m-%d_%H-%M-%S")
xprmnt_dir = time.strftime("/2022-03-10_23-17-39")


In [28]:
id_str = str(1)
bag_path_names = base_dset_dir + xprmnt_dir + '/' + id_str + '_*.bag' 
bag_path = glob.glob(bag_path_names)
bag_path

['/home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/1_2022-03-10-23-17-55.bag']

In [29]:
pos_path_name = base_dset_dir + xprmnt_dir + '/' + id_str + '_pos.npy'
# pos_path = glob.glob(pos_path_name)

proj_ori_path = base_dset_dir + xprmnt_dir + '/' + id_str + '_proj_ori.npy'

pos_ori_path_list = [pos_path_name, proj_ori_path]
pos_ori_path_list

['/home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/1_pos.npy',
 '/home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/1_proj_ori.npy']

In [30]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [42]:
dset = ScrewingDataset(bag_path[0], pos_ori_path_list, 5)
print(dset._len)
print(range(dset._len))
target, sample = dset[1]
print(sample)

print(sample.size())
# # print(dset._len)
length = len(dset)
train_size = 5
train_dset, test_dset = torch.utils.data.random_split(dset, [train_size,length - train_size])

[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/1_2022-03-10-23-17-55 already exists. Not creating.
62
range(0, 62)
tensor([[ 5.5467e-01,  1.8663e-03,  5.1567e-01,  9.9903e-01,  1.0498e-04,
         -5.8705e-03, -4.3688e-02, -8.2491e-01,  1.5947e+00, -3.2643e+00,
         -7.6325e-01,  6.7252e-01,  9.1588e-02, -2.0516e+00,  2.1062e+00,
         -1.5205e+00,  9.1957e+00,  9.6302e+00,  2.5714e+00],
        [ 5.5461e-01,  1.9187e-03,  5.1568e-01,  9.9896e-01,  1.6392e-04,
         -6.2453e-03, -4.5142e-02, -8.0139e-01,  1.2089e+00, -3.2347e+00,
         -6.3212e-01,  6.6832e-01,  6.6484e-02, -2.0545e+00,  1.3252e+00,
         -1.5246e+00,  5.3960e+00,  9.8766e+00, -3.9153e-01],
        [ 5.5456e-01,  1.9609e-03,  5.1569e-01,  9.9889e-01,  2.1905e-04,
         -6.6108e-03, -4.6553e-02, -7.8522e-01,  1.0652e+00, -3.2150e+00,
         -6.5998e-01,  6.3894e-01,  5.5834e-02, -1.8631e+00,  1.2982e+00,
         -1.4826e+00,  5.4218e+00,  8.8904e+00,  3.1933e

In [43]:
# len(train_dset)
len(test_dset)

57

In [62]:
dler = DataLoader(dset, batch_size=2, shuffle=True, num_workers=3)
for i, sample in enumerate(dler):
    print(sample[1].size())
    # print(sample.size())

torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])
torch.Size([2, 5, 19])


# Play around with concat dataset

In [63]:
num_dset = 10
dset_list = []
for i in range(num_dset):
    id_str = str(i)
    bag_path_names = base_dset_dir + xprmnt_dir + '/' + id_str + '_*.bag' 
    bag_path = glob.glob(bag_path_names)[0]

    pos_path_name = base_dset_dir + xprmnt_dir + '/' + id_str + '_pos.npy'
    proj_ori_path = base_dset_dir + xprmnt_dir + '/' + id_str + '_proj_ori.npy'
    pos_ori_path_list = [pos_path_name, proj_ori_path]
    
    dset_list.append(ScrewingDataset(bag_path, pos_ori_path_list, 5))
    
concat_dset = ConcatDataset(dset_list)

[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/0_2022-03-10-23-17-44 already exists. Not creating.
[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/1_2022-03-10-23-17-55 already exists. Not creating.
[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/2_2022-03-10-23-19-06 already exists. Not creating.
[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/3_2022-03-10-23-19-51 already exists. Not creating.
[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/4_2022-03-10-23-20-06 already exists. Not creating.
[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/5_2022-03-10-23-20-17 already exists. Not creating.
[INFO]  Data folder /home/serialexperimentsleon/datasets/screwing/2022-03-10_23-17-39/6_2022-03-10-23-20-31 already exists. Not creating.
[INFO]  Data folder /home/serialex

In [66]:
# DataLoader(dset, batch_size=2, shuffle=True, num_workers=3)
concat_loader = DataLoader(
    concat_dset,
    shuffle=True,
    num_workers=3,
    batch_size=2
)
# concat_dset

In [69]:
for i, sample in enumerate(concat_loader):
    # print(i)
    # print(sample[1].size())    
    print(sample)
    break

[tensor([[ 0.5701, -0.0145,  0.5115,  0.1104, -0.0727],
        [ 0.5670,  0.0099,  0.5103,  0.1730,  0.0889]], dtype=torch.float64), tensor([[[ 5.5270e-01, -6.7436e-03,  5.1559e-01,  9.9657e-01,  5.4972e-04,
          -1.2741e-02, -8.1736e-02, -1.3341e+00, -1.4029e+00, -3.1632e+00,
          -5.4503e-01,  5.7815e-01, -1.1581e-01, -8.7874e-01, -1.3663e+00,
          -1.4379e+00, -6.0464e+00,  3.4803e+00,  7.1104e+00],
         [ 5.5270e-01, -7.0267e-03,  5.1558e-01,  9.9650e-01,  4.5800e-04,
          -1.2783e-02, -8.2582e-02, -1.4143e+00, -1.3885e+00, -3.1888e+00,
          -6.0648e-01,  5.4831e-01, -1.1551e-01, -5.1456e-01, -1.1369e+00,
          -1.3600e+00, -4.8330e+00,  1.9033e+00,  6.5632e+00],
         [ 5.5273e-01, -7.2599e-03,  5.1559e-01,  9.9643e-01,  3.5905e-04,
          -1.2778e-02, -8.3437e-02, -1.4636e+00, -1.1349e+00, -3.2343e+00,
          -5.9630e-01,  5.5589e-01, -9.7680e-02, -5.9692e-01, -1.0307e+00,
          -1.3724e+00, -4.1527e+00,  9.8659e-01,  1.4355e+01],
  

In [45]:
import numpy as np

In [51]:
RT = np.array([
    [ -0.6356, -0.5383, 0.5534], 
    [0.7708, -0.4828, 0.4156],
    [0.0434, 0.6907, 0.7218 ]
])

T = np.array([
    [550/3275],
    [29260/3275],
    [110]
])
A = RT@T
A

array([[55.95789679],
       [41.5319426 ],
       [85.57624489]])

In [68]:
z_vec = np.random.rand(3)
print(z_vec[0:3])
z_vec[0:2] / z_vec[2]

test_path = '~/datasets/rosbags/'
test_path = os.path.expanduser(test_path)
test_file = 'test'



[0.90555912 0.461257   0.54141823]


In [69]:
np.pi


3.141592653589793

In [67]:

np.save(os.path.join(test_path, test_file), z_vec)
